### ISSUE TITLE
Compilation breaks UTF-8 characters

### ISSUE THREAD

**Issue by kempest** [acdvorak/intellij-lessc-plugin#38]
Hi,

I have a .less file with the following code:

``` css
a:before {
content: "► ";
}
```

The plugin produces the following output:

``` css
a:before {
content: "‚ñ∫ ";
}
```

I tested this on PHPStorm 5.0.4 and PHPStorm 6 EAP latest build. I am on a Mac Pro (10.7.5)

I also tried other utf-8 characters like umlauts. They are also broken in the compiled .css file.
The standalone mac Less.app works fine.
