### ISSUE TITLE
LESS CSS Compiler Error

### ISSUE THREAD

**Issue by aouicher** [acdvorak/intellij-lessc-plugin#52]
Soft: PHPStorm v6

i got an error with my less file

error message:

``` bash
15:15:44 LESS CSS Compiler Error
         style.less: Parse Error: Syntax Error on line 5 (line 5, column 1) near
         background-image: url(@path);
         @at2x_path: ~ '@{path}.replace(/\.\w+$/, function(match) { return "@2x" + match; })';
```

less file:

``` css
@highdpi: ~"(-webkit-min-device-pixel-ratio: 1.5), (min--moz-device-pixel-ratio: 1.5), (-o-min-device-pixel-ratio: 3/2), (min-resolution: 1.5dppx)";

.at2x(@path, @w: auto, @h: auto) {
 background-image: url(@path);
 @at2x_path: ~ '@{path}.replace(/\.\w+$/, function(match) { return "@2x" + match; })';

 @media @highdpi {
    background-image: url("@{at2x_path}");
    background-size: @w @h;
  }
}

body {
  background: #ffffff;
  font-size: 14px;
}


p {
  line-height: 1.4em;
  font-size: 14px;
}

/* Le code généré est uniquement destiné à visualiser votre création Reflow. */
.primaryContainer {
  height: auto;
  margin-left: auto;
  margin-right: auto;
  min-height: 100%;
  width: 960px;
  padding: 0px;
}

#box1 {
  float: left;
  height: 45px;
  margin-left: 0%;
  margin-top: 1px;
  clear: none;
  width: 100%;
/*  background-image: url('../images/bg-header.png');*/
  .at2x('../images/bg-header.png',auto,'45px');
  background-attachment: scroll;
  background-size: auto 45px;
  background-color: rgb(255, 255, 255);
  background-position: 0% 0%;
  background-repeat: repeat repeat;
}

body {
  background-attachment: fixed;
  background-color: rgb(255, 255, 255);
}

#image1 {
  float: left;
  margin-left: 0%;
  margin-top: 0px;
  clear: none;
  color: rgb(0, 0, 0);
  margin-right: 0px;
}

#image2 {
  float: right;
  margin-left: 0px;
  margin-top: 0px;
  clear: none;
  color: rgb(0, 0, 0);
  margin-right: 0px;
}

#image3 {
  float: left;
  width: 600px;
  max-width: 100%;
  height: auto;
  margin-left: 0%;
  margin-top: 0px;
  clear: none;
  color: rgb(0, 0, 0);
  min-width: 0px;
}

#box2 {
  float: left;
  height: auto;
  margin-left: 0%;
  margin-top: 0px;
  clear: none;
  width: 360px;
  min-height: 50px;
  min-width: 0px;
  background-color: rgb(31, 30, 35);
  padding: 4%;
  margin-right: 0px;
}

#reflow-dbf04b46-bd7c-a148-6fe7-58d4fa508af1 {
}

#text1 {
  float: left;
  font-size: 0.9em;
  color: rgb(255, 255, 255);
  width: auto;
  height: auto;
  text-align: left;
  font-weight: 400;
  line-height: 1.2em;
  word-wrap: break-word;
  margin-left: 0px;
  margin-top: 0px;
  clear: none;
  min-height: 0px;
  min-width: 0.5em;
  font-family: 'trebuchet ms';
  margin-bottom: 17px;
}

#reflow-3872a9b9-45dd-cb14-9c86-c655a7ef9003 {
}

#text2 {
  float: left;
  font-size: 14px;
  color: rgb(192, 192, 192);
  width: auto;
  height: auto;
  text-align: left;
  font-weight: 400;
  line-height: 1.4em;
  word-wrap: break-word;
  margin-left: 0%;
  margin-top: 0px;
  clear: both;
  min-height: 0px;
  min-width: 0px;
  margin-right: 0px;
  margin-bottom: 10px;
}

#box3 {
  float: left;
  height: auto;
  margin-left: 0%;
  margin-top: 0px;
  clear: none;
  width: 360px;
/*padding: 4%;*/
}

#reflow-78317aa6-40ba-5e12-74e0-7ed079b62219 {
}

#reflow-b5082403-e854-fd43-fa51-b2a110222df1 {
}

#text3 {
  float: left;
  font-size: 14px;
  width: 100%;
  height: auto;
  text-align: left;
  font-weight: 400;
  line-height: 1.7em;
  word-wrap: break-word;
  margin: 0px;
  clear: none;
  min-height: 0px;
  min-width: 0px;
  padding: 12px;
  color: #1f1e21;
}

#reflow-a2a2179f-6376-c53c-0906-abab903f1e4c {
}

#reflow-af1ffbd6-2b41-817e-dc5b-b4837813a4b1 {
}

.fleche {
  display: none;
}

@media screen and (max-width: 480px) {
  .fleche {
    display: block;
    float: right;
    margin-top: -30px;
    margin-left: 10px;
    height: 125px;
  }

  #box3 {
    margin: 0px;
    clear: both;
    width: 100%;
  }

  #text3 {
    margin: 0px;
    clear: none;
  }

  #box2 {
    width: 100%;
    margin: 0px;
    clear: both;
  }

  #image3 {
    width: 100%;
    max-width: none;
  }

  .primaryContainer {
    width: 100%;
  }

  #form_record {
    padding: 12px;
  /*    background-image: url('../images/bg-form.jpg');*/
    .at2x('../images/bg-form.jpg',10px,'10px');
    background-size: 10px 10px;
    background-repeat: repeat repeat;

  }

  #box5 img.float-right {
    float: right;
  }

  #box5 p,
  #box4_1 p {
    padding-left: 12px;
    padding-top: 10px;
    line-height: 1.7em;
    color: #1f1e21;
    font-size: 14px;
  }

  #box6 {
    padding-left: 12px;
    padding-top: 10px;
  }

  h2 {
    border-bottom: 6px solid #000000;
    padding-left: 12px;
    margin: 0;
    height: 26px;
    line-height: 26px;
  }

}

input.input {
  border-radius: 0;
  border: 1px solid #000000;
  margin: 7px 0;
  width: 100%;
  padding: 5px;
}

#figaromedias_bundle_ateliersbundle_recordtype_EmailRecord {
  margin-bottom: 14px;
}

input[type="checkbox"] {
  display: none;
}

input[type="checkbox"] + label.checkForm {
  font-size: 12px;
}

input[type="checkbox"] + label.checkForm span {
  display: inline-block;
  width: 30px;
  height: 30px;
  margin: -1px 4px 0 0;
  vertical-align: middle;
  background: url('../images/checkbox@2x.png');
  background-position: left top;
  background-size: 62px 30px;
  background-repeat: no-repeat;
  cursor: pointer;
  float: left;
}

input[type="checkbox"] + label.checkForm div {
  padding-left: 40px;
  vertical-align: middle;
}

input[type="checkbox"]:checked + label.checkForm span {
  background-position: -32px top;
  width: 30px;
  height: 30px;
  margin: -1px 4px 0 0;
  vertical-align: middle;
}

.bt_submit {
  border-radius: 0;
  margin-top: 10px;
  .at2x('../images/bt_valider.png',52px,'12px');
  background-size: 52px 12px;
  background-position: center center;
  background-repeat: no-repeat;
  background-color: #dc0000;
  width: 295px;
  height: 30px;
  border: 0;
}

.bt_reglement {
  border-radius: 0;
  margin-top: 10px;
  margin-bottom: 15px;
  .at2x('../images/bt_reglement.png',171px,'16px');
  background-size: 171px 16px;
  background-position: center center;
  background-repeat: no-repeat;
  background-color: #a8a8a8;
  width: 295px;
  height: 30px;
  border: 0;
  display: block;
}

.checkForm {
/*  float: left;*/
  margin-right: 12px;
}

#wrapper {
  width: 100%;
  overflow: auto;
}

#scroller {
  width: 1000px;
  float: left;
  padding: 0;
}

#scroller ul {
  list-style: none;
  display: block;
  float: left;
  width: 100%;
  height: 100%;
  padding: 0;
  margin: 0;
}

#scroller li {
  display: block;
  float: left;
  height: 200px;
  text-align: center;
  border-right: 3px solid #ffffff;
}

.bt_share {
  display: inline-block;
  margin-right: 6px;
}

#box4_1 {
/*display: none;*/
}
```

**Comment by aouicher** [comment]
issue closed

right syntax:

``` css
.at2x(@path, @w: auto, @h: auto) {
 background-image: url(@path);
 @at2x_path: ~'@{path}.replace(/\.\w+$/, function(match) { return "@2x" + match; })';
```

``` css
~'@{path}
```

not

``` css
~ '@{path}
```
